var porn = `
# Porn sites
101boyvideos.com
101hotguys.com
18boybeauty.com
18gayteen.com
24hentai.com
4boystube.com
69games.xxx
88fuck.com
abouttwinks.com
actual-porn.org
adultblogtoplist.com
adultvideofinder.com
allboner.com
allgayteenboys.com
alluncutcocks.tumblr.com
alotporn.com
alphamusclehunks.tumblr.com
always-nude.tumblr.com
amateur-gay-sex-videos-only.tumblr.com
amateur-gay-sex-videos.tumblr.com
amateurgaylovin.tumblr.com
amazon.com
analgaytwinks.com
anotherpornblog.tumblr.com
apetube.com
apina.biz
asiandragons.tumblr.com
avn.com
awsum.me
babe-lounge.com
babepedia.com
badjojo.com
beachandpool.net
beardsandforeskin.tumblr.com
befuck.com
best-paypornsites.com
bestpornstardb.com
big-dick-pics.tumblr.com
big-thick-hard-uncut-cock.tumblr.com
bigdickclub.tumblr.com
bigggggggggggg.tumblr.com
blackcock.tumblr.com
blackgayporno.tumblr.com
bonertube.com
bootytape.com
borrowedmalecelebs.tumblr.com
boy18tube.com
boycall.com
boycollector.net
boyfriendtv.com
boyself.com
boysontube.com
boyspiss.tumblr.com
boywankblog.com
bravotube.net
camtogays.com
capullos.tumblr.com
celebuzz.com
chan.sankakucomplex.com
chulazosxxx.com
cutegaytwink.com
daftporn.com
dailee.com
dansmovies.com
definebabe.com
deviantclip.com
dirtyrottenwhore.com
dragonballzyaoi.com
drtuber.com
efukt.com
elephanttube.com
entnt.com
eporner.com
erikforeskin.tumblr.com
erooups.com
erotica7.com
eroxia.com
expmceleb.tumblr.com
extremetube.com
fakku.net
famous-skin.tumblr.com
famousmennakeduk.tumblr.com
fapdu.com
femdom-tube.xxx
findtubes.com
fistingdudes.tumblr.com
fistingmen.tumblr.com
foreskin1.tumblr.com
fortheloveofasianmen.tumblr.com
forum.oneclickchicks.com
forum.xnxx.com
forumophilia.com
freegayporn.com
freeones.com
freudbox.com
fuckuh.com
fuckyeahhugepenis.tumblr.com
funnyboy86.tumblr.com
furrific.tumblr.com
fuskator.com
fux.com
gay-boy-sex.net
gay-daddy-mature-videos.tumblr.com
gay-wet-dreams-returns.tumblr.com
gay.sex.com
gayandpissingguys.tumblr.com
gaybearmatt.tumblr.com
gayfuror.com
gayfurryfun.tumblr.com
gaymaletube.com
gaypissingmen.tumblr.com
gayplanet.easyxtubes.com
gaypornium.com
gayrookievideos.com
gayroulettechat.com
gaysexishilarious.tumblr.com
gaysteensboys.com
gayteenboylinks.com
gayteenlove.com
gayteenvideo.org
gaytube.com
gayvideoshack.tumblr.com
gelbooru.com
givemegay.com
gkbdsm.tumblr.com
gmlc1213.tumblr.com
gotenboner.com
gotgayporn.com
guystricked.com
h2porn.com
hairyhunkymen.tumblr.com
hairymeat.tumblr.com
handsomedaddies.tumblr.com
hard-yaoi.tumblr.com
hclips.com
hdhentaisex.com
hdporn.net
hentai-foundry.com
hentai.tc
hentai4manga.com
hentairules.net
hentaischool.com
hide-porn.winsite.com
holeboy.tumblr.com
hollywoodlife.com
homosexualtube.com
hot-celebrity-fakes.tumblr.com
hotandnaked99.tumblr.com
hotbears.tumblr.com
hotgaycartoons.tumblr.com
hotgaylist.com
hugethingsss.tumblr.com
hunkdude.tumblr.com
hunkytwinks.tumblr.com
icantbelievehesnaked.tumblr.com
ilovecockuncut.tumblr.com
imagearn.com
incestandotherstuff.tumblr.com
intactguys.com
intactmen.tumblr.com
intostraightnakedguys.tumblr.com
inxporn.com
itsallgay.eu
itsnotpornipromise.tumblr.com
jailcop.tumblr.com
jockdad38.tumblr.com
jockertube.com
jocknights.com
justjared.com
justusboys.com
keepersecurity.com
keezmovies.com
kindgirls.com
laineygossip.com
largethickcock.tumblr.com
latinadmirer.tumblr.com
linkcollector.net
lockerroomguys.tumblr.com
lolhentai.net
lustpin.com
luv4daddy.tumblr.com
madthumbs.com
majdad-celebs.tumblr.com
malecelebritynudes.tumblr.com
manhub.com
manpussymania.tumblr.com
manroulette.com
maturechang.tumblr.com
maturegaystories.com
maxim.com
mediadetective.com
mefffisto.tumblr.com
megiant1.tumblr.com
mexigreek.tumblr.com
militaryhotness.tumblr.com
militarymen.tumblr.com
militarymenglory.tumblr.com
milkingcocks.tumblr.com
milliondicks.eu
mofosex.com
myfavgayvideos.tumblr.com
myhentai.tv
mypornbible.com
myporngay.com
myxvids.com
naked-straight-men.tumblr.com
nakedguys99.tumblr.com
nakednews.com
nkdmalecelebs.tumblr.com
nudevista.com
nurglesnymphs.com
nuvid.com
obeyyourfather.tumblr.com
onlydudes.com
onlygaystories.com
oofahpapa.tumblr.com
orgasm.com
oztwink.tumblr.com
pdxsuitsucker.tumblr.com
peachyforum.com
perezhilton.com
pervclips.com
petebrownuk.tumblr.com
phapit.com
phun.org
pichack.com
pissandgroan.tumblr.com
planetsuzy.org
playforceone.com
playporngames.com
plublogs.com
porn-wanted.com
pornative.com
pornbb.org
pornbits.net
porncor.com
pornerbros.com
pornheed.com
pornhost.com
pornhub.com
pornhunks.tumblr.com
pornicom.com
pornjog.com
pornmaxim.com
pornmd.com
pornpin.com
pornplanner.com
pornrabbit.com
porntitan.com
proporn.com
punchpin.com
pussytorrents.org
randomale.net
ricanguys.tumblr.com
rockettube.com
savvyifyanasty.tumblr.com
seniorsan.tumblr.com
sexforums.com
sextubespot.com
sexwithdad.tumblr.com
sexyfuckgames.com
sexymatureworldwide.tumblr.com
simply-hentai.com
slutload.com
small-cut-cock.tumblr.com
smutty.com
soft-flaccid-uncut-cock.tumblr.com
spankbang.com
speci-men.tumblr.com
spyboy24.tumblr.com
spycamfromguys.com
spyonmales.tumblr.com
straightguynaked.tumblr.com
straightguyscocksout.tumblr.com
sunporno.com
surfgayvideo.com
sweetasiantwinks.tumblr.com
teenboysrank.com
teensbodybuilding.tumblr.com
teensgaysvideo.com
the-pork.com
theboyrook.tumblr.com
thegayteentube.com
thehollywoodgossip.com
thenewporn.com
thick-cocks.tumblr.com
thongsaroundtheworld.com
tjoob.com
tnaflix.com
topfreepornvideos.com
totallynsfw.com
tube8.com
tubegalore.com
tubehentai.com
tubewankers.com
twinkblog.pichack.com
twinkteencum.tumblr.com
txbibear.tumblr.com
updatetube.com
uselessjunk.com
userporn.com
vintagepinupgirls.net
vpornvideos.com
wankoz.com
wattube.com
wetplace.com
woofy-bears.tumblr.com
wreckedbybbc.tumblr.com
wtfpeople.com
xbabe.com
xhamster.com
xnxx.com
xvideos.com
xxxbunker.com
xxxymovies.com
yaoi-games.com
yeswegays.com
youjizz.com
youngboyvideos.com
youngerforeskin.tumblr.com
youporn.com
youporngay.com
youramateurporn.com
yourlustmovies.com
yummy-yaoi.tumblr.com
`
